In [7]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
from PIL import Image
img = Image.open('full_duck.jpg') 
img_array = np.array(img)/255.0  #full duck array

In [8]:
duck_mode0=Image.open('duc.jpg')  #duck_model
duck_array = np.array(duck_mode0)/255.0

#duck_model mu
total=duck_array.shape[0]*duck_array.shape[1] #像素點總和

duck_x = 0 #duck_model's RGB array
duck_y = 0
duck_z = 0

for j in range(duck_array.shape[0]):  #每個像素點
      for i in range(duck_array.shape[1]): 
           duck_x = duck_x + duck_array[j][i][0] 
           duck_y = duck_y + duck_array[j][i][1]
           duck_z = duck_z + duck_array[j][i][2]

a= duck_x /total #RGB array's mu
b= duck_y /total
c= duck_z /total

duck_mu=[a,b,c]  #duck_model mu
print(duck_mu)


#duck_model sigma
covar_x=0

for j in range(duck_array.shape[0]):  #像素點總和  
     for i in range(duck_array.shape[1]): 
            x_reduce_mu   =  duck_array[j][i]-duck_mu
            x_reduce_mu_T =  np.transpose([x_reduce_mu])
            covar_x = covar_x + ( x_reduce_mu * x_reduce_mu_T )
            
print(covar_x /(total-1))


[0.9329302832244177, 0.9772287581699506, 0.9890348583878087]
[[0.00048767 0.00043168 0.00022894]
 [0.00043168 0.00042381 0.00024042]
 [0.00022894 0.00024042 0.00018024]]


In [9]:
no_duck_mode1=Image.open('noduc1.jpg')#noduc1
no_duck_array1 = np.array(no_duck_mode1)/255.0
#noduc1 mu
total_noduck = no_duck_array1.shape[0]*no_duck_array1.shape[1] #像素點

no_duck1_x = 0
no_duck1_y = 0
no_duck1_z = 0

for j in range(no_duck_array1.shape[0]):   
    for i in range(no_duck_array1.shape[1]): 
        no_duck1_x = no_duck1_x + no_duck_array1[j][i][0]
        no_duck1_y = no_duck1_y + no_duck_array1[j][i][1]
        no_duck1_z = no_duck1_z + no_duck_array1[j][i][2]

a2= no_duck1_x /total_noduck
b2= no_duck1_y /total_noduck
c2= no_duck1_z /total_noduck

no_duck1_mu=[a2,b2,c2]
#noduc1.jpg  sigma
print(no_duck1_mu)
no_covar1_x=0

for j in range(no_duck_array1.shape[0]):   
    for i in range(no_duck_array1.shape[1]): 
        x_reduce_mu_no   =  no_duck_array1[j][i]-no_duck1_mu
        x_reduce_mu_no_T =  np.transpose([x_reduce_mu_no])
        no_covar1_x      = no_covar1_x + ( x_reduce_mu_no * x_reduce_mu_no_T )
print(no_covar1_x /(total_noduck-1))                

[0.17408301502419837, 0.2320264833206075, 0.2095136236312761]
[[ 6.74976177e-06  1.79392705e-06  6.18058750e-06]
 [ 1.79392705e-06  6.42222372e-06 -2.10807823e-06]
 [ 6.18058750e-06 -2.10807823e-06  3.93955411e-05]]


In [10]:
no_duck_mode2=Image.open('noduc2.jpg')#noduc2
no_duck_array2 = np.array(no_duck_mode2)/255.0
#noduc1 mu
total_noduck = no_duck_array2.shape[0]*no_duck_array2.shape[1] #像素點

no_duck2_x = 0
no_duck2_y = 0
no_duck2_z = 0

for j in range(no_duck_array2.shape[0]):   
    for i in range(no_duck_array2.shape[1]): 
        no_duck2_x = no_duck2_x + no_duck_array2[j][i][0]
        no_duck2_y = no_duck2_y + no_duck_array2[j][i][1]
        no_duck2_z = no_duck2_z + no_duck_array2[j][i][2]

a3= no_duck2_x /total_noduck
b3= no_duck2_y /total_noduck
c3= no_duck2_z /total_noduck

no_duck2_mu=[a3,b3,c3]
#noduc2.jpg  sigma
 
no_covar2_x=0

for j in range(no_duck_array2.shape[0]):   
    for i in range(no_duck_array2.shape[1]): 
        x_reduce_mu_no   =  no_duck_array2[j][i]-no_duck2_mu
        x_reduce_mu_no_T =  np.transpose([x_reduce_mu_no])
        no_covar2_x      =  no_covar2_x + ( x_reduce_mu_no * x_reduce_mu_no_T )
            

In [11]:
no_duck_mode3=Image.open('noduc5.jpg')#noduc5
no_duck_array3 = np.array(no_duck_mode3)/255.0
#noduc1 mu
total_noduck = no_duck_array3.shape[0]*no_duck_array3.shape[1] #像素點

no_duck3_x = 0
no_duck3_y = 0
no_duck3_z = 0

for j in range(no_duck_array3.shape[0]):   
    for i in range(no_duck_array3.shape[1]): 
        no_duck3_x = no_duck3_x + no_duck_array3[j][i][0]
        no_duck3_y = no_duck3_y + no_duck_array3[j][i][1]
        no_duck3_z = no_duck3_z + no_duck_array3[j][i][2]

a4= no_duck3_x /total_noduck
b4= no_duck3_y /total_noduck
c4= no_duck3_z /total_noduck

no_duck3_mu=[a4,b4,c4]
#noduc2.jpg  sigma
 
no_covar3_x=0

for j in range(no_duck_array3.shape[0]):   
    for i in range(no_duck_array3.shape[1]): 
        x_reduce_mu_no   =  no_duck_array3[j][i]-no_duck3_mu
        x_reduce_mu_no_T =  np.transpose([x_reduce_mu_no])
        no_covar3_x      =  no_covar3_x + ( x_reduce_mu_no * x_reduce_mu_no_T )
            

In [12]:
import PIL 
im = PIL.Image.new(mode = "RGB", size = img.size )
import math
im_array= np.array(im) 

PI=math.pi
DET=np.linalg.det(covar_x)
INVERSE= np.linalg.inv(covar_x)
EXP=[]

DET2=np.linalg.det(no_covar1_x)
INVERSE2= np.linalg.inv(no_covar1_x)
EXP2=[]

DET3=np.linalg.det(no_covar2_x)
INVERSE3= np.linalg.inv(no_covar2_x)
EXP3=[]

DET4=np.linalg.det(no_covar3_x)
INVERSE4= np.linalg.inv(no_covar3_x)
EXP4=[]


for j in range(img_array.shape[0]): #full_duck's every point  
    for i in range(img_array.shape[1]): 
        a=img_array[j][i]-duck_mu 
        a1=np.transpose([img_array[j][i]-duck_mu]) 
        a2=np.dot(a,INVERSE) 
        a3=np.dot(a2,a1)
        a4=1/( ( ( (2*PI)**3 )*DET )**0.5 ) * math.e**((-0.5)*a3 )

        
        c=img_array[j][i]-no_duck1_mu 
        c1=np.transpose([img_array[j][i]-no_duck1_mu]) 
        c2=np.dot(c,INVERSE2) 
        c3=np.dot(c2,c1)
        c4=1/( ( ( (2*PI)**3 )*DET2 )**0.5 ) * math.e**((-0.5)*c3 )

        
        d=img_array[j][i]-no_duck2_mu 
        d1=np.transpose([img_array[j][i]-no_duck2_mu]) 
        d2=np.dot(d,INVERSE3) 
        d3=np.dot(d2,d1)
        d4=1/( ( ( (2*PI)**3 )*DET3 )**0.5 ) * math.e**((-0.5)*d3 )

        
        f=img_array[j][i]-no_duck3_mu 
        f1=np.transpose([img_array[j][i]-no_duck3_mu]) 
        f2=np.dot(f,INVERSE4) 
        f3=np.dot(f2,f1)
        f4=1/( ( ( (2*PI)**3 )*DET4 )**0.5 ) * math.e**((-0.5)*f3 )

        

        
        if(a4>c4 and a4>d4 and a4>f4):
            im_array[j][i]=[255,255,255] #白色
        else:
            im_array[j][i]=[0,0,0] #黑色
                
 

In [13]:
im=Image.fromarray(im_array) # numpy轉image类
im.show() #顯示圖片
         